package net.AspectNetwork.bditt.API.enums;


import org.bukkit.Material;

public class ItemUtilEnum {

  public static final ItemType OTHER_UNSTACKABLE_ITEMS = new ItemType(new Material[] {
      Material.ENCHANTED_BOOK,
      Material.POTION,
      Material.LEGACY_BOOK_AND_QUILL,
      Material.FLINT_AND_STEEL,
      Material.MINECART,
      Material.LEGACY_COMMAND_MINECART,
      Material.LEGACY_EXPLOSIVE_MINECART,
      Material.HOPPER_MINECART,
      Material.LEGACY_POWERED_MINECART,
      Material.LEGACY_STORAGE_MINECART,
      Material.WATER_BUCKET,
      Material.LAVA_BUCKET,
      Material.MILK_BUCKET,
      Material.MAP,
      Material.SADDLE,
      Material.LEGACY_CARROT_STICK,
      Material.LEGACY_BOAT,
      Material.LEGACY_RECORD_10,
      Material.LEGACY_RECORD_11,
      Material.LEGACY_RECORD_12,
      Material.LEGACY_RECORD_9,
      Material.LEGACY_RECORD_8,
      Material.LEGACY_RECORD_7,
      Material.LEGACY_RECORD_6,
      Material.LEGACY_RECORD_5,
      Material.LEGACY_RECORD_4,
      Material.LEGACY_RECORD_3,
      Material.LEGACY_GOLD_RECORD,
      Material.LEGACY_GREEN_RECORD
  });
  public static final ItemType INTERFACABLE_TILE_ENTITIES = new ItemType(new Material[] {
      Material.DISPENSER,
      Material.NOTE_BLOCK,
      Material.LEGACY_BED_BLOCK,
      Material.CHEST,
      Material.LEGACY_WORKBENCH,
      Material.FURNACE,
      Material.LEGACY_BURNING_FURNACE,
      Material.LEGACY_WOODEN_DOOR,
      Material.ACACIA_DOOR,
      Material.BIRCH_DOOR,
      Material.DARK_OAK_DOOR,
      Material.IRON_DOOR,
      Material.JUNGLE_DOOR,
      Material.SPRUCE_DOOR,
      Material.LEVER,
      Material.REDSTONE_ORE,
      Material.STONE_BUTTON,
      Material.JUKEBOX,
      Material.LEGACY_CAKE_BLOCK,
      Material.LEGACY_DIODE_BLOCK_ON,
      Material.LEGACY_DIODE_BLOCK_OFF,
      Material.LEGACY_TRAP_DOOR,
      Material.LEGACY_FENCE_GATE,
      Material.LEGACY_ENCHANTMENT_TABLE,
      Material.BREWING_STAND,
      Material.DRAGON_EGG,
      Material.ENDER_CHEST,
      Material.LEGACY_COMMAND,
      Material.BEACON,
      Material.LEGACY_WOOD_BUTTON,
      Material.ANVIL,
      Material.TRAPPED_CHEST,
      Material.LEGACY_REDSTONE_COMPARATOR_ON,
      Material.LEGACY_REDSTONE_COMPARATOR_OFF,
      Material.HOPPER,
      Material.ACACIA_FENCE_GATE,
      Material.BIRCH_FENCE_GATE,
      Material.DARK_OAK_FENCE_GATE,
      Material.LEGACY_FENCE_GATE,
      Material.JUNGLE_FENCE_GATE,
      Material.SPRUCE_FENCE_GATE,
      Material.DROPPER

  });
}
