name: AspectEnchantments
main: net.AspectNetwork.bditt.Main
version: 0.0.1
api-version: 1.14
commands:
   aenchant:
      description: Enchant a custom enchantment.
      usage: /aenchant <enchantment>